### ISSUE TITLE
Fix fiat names

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/xchange-crawler#10]
Turkish Lira
Russian Rubble
Ghanaian Cedi
etc...

**Comment by nxtpool** [comment]
TRL = not Turkish Lira but TrollCoin
GHS = not Ghanaian Cedi but Giga Hash per Second 
GHC = not Ghanaian Cedi but GamerholicCoin
etc.
Should we filter them out?

**Comment by 21xhipster** [comment]
Yes.

**Comment by nxtpool** [comment]
Filtered out:
TRL = not Turkish Lira but TrollCoin
GHS = not Ghanaian Cedi but Giga Hash per Second 
GHC = not Ghanaian Cedi but GamerholicCoin
MYR = not Malaysian Ringgit but MyriadCoin
XAU = not Gold but Xaurum
BOB = not Bolivian Boliviano but DobbsCoin
CRC = not Costa Rican Colón but CraftCoin
XBC = not European Unit of Account but Bitcoin Plus
XXX = not Unknown Currency but XXXCoin
CYP = not Cypriot Pound but Cypher
