### ISSUE TITLE
Running without Maven

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/xchange-crawler#10]
@nxtpool I look into containerizing xchang-crawler and I'd like an ability to run it without Maven and all artifacts produced as a result of build process. Can you point me to instructions to get binary that I can deploy along with its config?

**Comment by nxtpool** [comment]
To create binaries:
mvn install dependency:copy-dependencies

To run without maven you need:
xchange-crawler-0.1.0.jar
lib/*.jar

Run command:
java -cp xchange-crawler-0.1.0.jar:lib/* fund.cyber.xchange.Main

**Comment by abitrolly** [comment]
I still don't have JDK installed to validate the instruction. Let's make an end2end test for the binary.

**Comment by nxtpool** [comment]
To have access to xchange crawler configuration (crawler.config) just Run commands:
unzip xchange-crawler-0.1.0.jar
java -cp .:dependency/* fund.cyber.xchange.Main

**Comment by abitrolly** [comment]
Are there any reasons why we can't just make `.jar` that can be run with simple:

    java -jar java xchange-crawler-0.1.0.jar

And add two parameters to it:

    -h, --help
    -c, --config

? It will greatly simplify our deployment instructions and automated config management.

**Comment by nxtpool** [comment]
The reason is dependencies

**Comment by abitrolly** [comment]
Can this help https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven ?

**Comment by nxtpool** [comment]
What for?

**Comment by nxtpool** [comment]
I have given you a command you can use.

**Comment by abitrolly** [comment]
It is not for me. We are making open source product, which is supposed to be run by users.

**Comment by abitrolly** [comment]
But I lied. It will be also easier for me to write documentation how to run our cybernode. =)

**Comment by nxtpool** [comment]
If we have crawler.properties outside jar we cannot use 'java -jar xchange-crawler-0.1.0.jar [parameters]' anyway.

**Comment by nxtpool** [comment]
But I'm not sure if we need it will be configurable or not...

**Comment by abitrolly** [comment]
I don't understand the problem why it is impossible to have default parameters if `crawler.properties` is absent?

**Comment by abitrolly** [comment]
We definitely need it configurable if we want a cluster. Connection will be managed outside of our code.

**Comment by abitrolly** [comment]
So server and port addresses should never be hardcoded.

**Comment by nxtpool** [comment]
so you have at least two files

**Comment by abitrolly** [comment]
Right. Binary is managed by deployment procedure from binary repositories, and config is setup and kept in version control by configuration management software.

**Comment by nxtpool** [comment]
ok I'll try to do that

**Comment by abitrolly** [comment]
Would be awesome. Thank you. =)

**Comment by nxtpool** [comment]
https://github.com/cyberFund/xchange-crawler/pull/27
https://github.com/cyberFund/xchange-crawler/pull/28
