### ISSUE TITLE
CI: Setup continuous delivery to GitHub

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/xchange-crawler#18]
I thought about adding artifact upload to https://www.jfrog.com/open-source/#bintray but handling another service looks like another link in the long chain to care about, so I will setup publishing of everything that builds correctly as pre-release [binaries to GitHub](https://developer.github.com/v3/repos/releases/#create-a-release).

Every release will create a new tag. This means we need to choose versioning for our project, but I am fine with timestamps for now.

**Comment by abitrolly** [comment]
@litvintech https://github.com/cyberFund/xchange-crawler/commit/84cb5b763592ec9a66e02a6c05a351f69cfa498e need an encrypted travis deploy token for github to close this ticket.

**Comment by abitrolly** [comment]
@litvintech ping. =)

**Comment by abitrolly** [comment]
Travis [GitHub releases](https://github.com/travis-ci/dpl#github-releases) plugin supports only OAuth tokens for deployment. These tokens are [per user](https://docs.travis-ci.com/user/private-dependencies/#API-Token), not per repository. To use per-repository deploy keys, we need [script releases](https://docs.travis-ci.com/user/deployment/script/) with custom [SSH key encryption](https://djw8605.github.io/2017/02/08/deploying-docs-on-github-with-travisci/). To avoid storing keys on disk, try to pipe/read it into `ssh-add` from `/dev/stdin`.

**Comment by abitrolly** [comment]
Problem with installing `travis` on Ubuntu - https://github.com/travis-ci/travis.rb/issues/512 (PR submitted)

**Comment by abitrolly** [comment]
https://github.com/travis-ci/dpl/issues/650 - upstream issue to track for deploy keys support in `releases` plugin.

**Comment by abitrolly** [comment]
Install `travis`
```
apt install ruby ruby-dev gcc make
gem install travis -v 1.8.8 --no-rdoc --no-ri
```
Encrypt key
```
travis login --org
travis encrypt-file -r cyberFund/xchange-crawler deploy_key
```
Commit `deploy_key.enc` into repository and record `openssl` line in `.travis.yml`, https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption for details.

**Comment by abitrolly** [comment]
**UPDATE**: Releasing on GitHub with deploy keys won't work. Release API is only exposed to personal OAuth token. Need to generate one and encrypt.

**Comment by litvintech** [comment]
@abitrolly what is the status of this task?

**Comment by abitrolly** [comment]
@litvintech last time I tried to setup Circle CI and Travis CI as a GitHub App from Marketplace, but they are still OAuth Apps. Time was spent to figure out the difference. OAuth App acts on your behalf and can access to all your repositories, which is bad, but we have no choice right now, because no CI service for GitHub is ready for new API.

As for fixing specific Travis CI authentication problem, it looks like delivery pipeline needs a tag to make releases. I am in the process, because I need those binaries.

**Comment by abitrolly** [comment]
Automatic binaries from `master` are available as `Pre-release` with `untagged-hash` label.

https://github.com/cyberFund/xchange-crawler/releases/tag/untagged-e9937e939f50d3200345
generated from
https://travis-ci.org/cyberFund/xchange-crawler/builds/243248934#L881
