### ISSUE TITLE
CI/CD: Polish GitHub releases

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/xchange-crawler#36]
There are multiple issues with GitHub releases (#18).

Deploy for `master` creates new `untagged-` tags, **deploy tags create new commits that get tested again**. They are not deployed with `Skipping a deployment with the releases provider because this branch is not permitted`. But enabling `on: tags` in `.travis.yml` may potentially create infinite loop, but probably won't, because tag already exists. There could be a way to add `[skip ci]` to those tag commits to skip extra builds.

**Release by tag doesn't work**. Normal releases https://github.com/cyberFund/xchange-crawler/releases/tag/v0.1 are created manually.

`untagged-` release names are better to be replaced by `nightly-` or `dev-`.

**Comment by litvintech** [comment]
@abitrolly what is the progress for this task? 
I added protection for master branch for merging only throw PRs

**Comment by abitrolly** [comment]
1. [ ] implement and test releases for tagged builds
2. [ ] stop builds for `untagged-` tags

I don't know how to do this. Need more time to read Travis CI code. Here is related issue for the start https://github.com/travis-ci/dpl/issues/585 Travis CI `dpl` is in Ruby, uses Octokit client to GitHub API. It may be the case that it passes flags from `.travis.yml` to GitHub API as-is, so if our use case can be solved through raw GitHub API (and it looks possible), it can be solved through few patches to Travis CI.

**Comment by abitrolly** [comment]
If we can offload this task to some Ruby students - that would be ideal.

**Comment by abitrolly** [comment]
* [ ] change release names from `untagged` to `devbuid` https://github.com/travis-ci/travis-ci/issues/7624#issuecomment-294938921

**Comment by abitrolly** [comment]
Travis CI indeed passes unknown options from `.travis.yml` to Octokit - https://github.com/travis-ci/docs-travis-ci-com/pull/1273 - so at least naming releases in possible.

**Comment by abitrolly** [comment]
This [didn't work](https://github.com/cyberFund/xchange-crawler/blob/26d495a1e4f70be5cf8c341ebe48aa821111f17a/.travis.yml#L28) for [body](https://octokit.github.io/octokit.rb/Octokit/Client/Releases.html#create_release-instance_method) option - https://travis-ci.org/cyberFund/xchange-crawler#L1378

**Comment by abitrolly** [comment]
No more actual for this project.
