### ISSUE TITLE
Lets rethink global architecture together.

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/xchange-crawler#44]
Hello guys,

Lets discuss next points:

1.  Should we use **HTTP api** pull strategy or we should chose **websocket** way where possible?

HTTP api drawbacks: 
- we can pull data only for one currency pair. Thats lead to dozens of requests to update all currencies.
- some exchange markets allow to do only N requests per second. (ex: Poloniex - 6r/s)
- not well defined XChange library. For each given market, we don't know how many entities we will get for current requests, order of entities and etc. Thats lead to addition machine resources consumptions for cutting same entities from different 

Websocket (wamp) drawbacks:
- there is not well enough java library for wamp implementation (if you compare java libraries to pythons)
- not all markets has wamp api (need research)
2.  If server failed due some reason for hour, should we pull and index all missed data? 
- may be not all markets allow to query entities for time range

**Comment by litvintech** [comment]
1. xchange was developed powered by constraints witch each different for every exchange - I mean apis, rates, interfaces, general functionality..
so, we should use everything what exchanges provide
2. yes, from moment when we start crawler in production we should guarantee continuity of data

**Comment by litvintech** [comment]
@hleb-albau how it's going, buddy?

**Comment by abitrolly** [comment]
XChange library is polling-only - https://github.com/timmolter/XChange/issues/1476#issuecomment-310429552 Does WebSocket allow polling?
