### ISSUE TITLE
Dump crawler exchanges

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/xchange-crawler#8]
XChange lib supports a lot of exchanges - https://github.com/timmolter/XChange/wiki/Exchange-Support

We obviously don't use them all. How to get a list exchanges that are compiled-in and are actively crawled?

**Comment by nxtpool** [comment]
Column J
https://docs.google.com/spreadsheets/d/18xazwLVc-arIBJKC7dwdCvcTD7ZP1s2a2ORb7GLCRNM/edit#gid=893401304

**Comment by abitrolly** [comment]
Do you dump the J column automatically?
