### ISSUE TITLE
Fix "Unknown Currency"

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/xchange-crawler#9]

**Comment by 21xhipster** [comment]
- [ ] Unknown Currency
- [ ] DD
- [ ] BC
- [ ] European Unit of Account (XBC)
- [ ] DRK

**Comment by nxtpool** [comment]
Unknown Currency = XXX = XXXCoin
DRK = Dash
DD = Dogecoindark
BC = BlackCoin
European Unit of Account (XBC) = XBC = Bitcoin Plus
